config/routes.rb
Dungeons::Application.routes.draw do
  root :to => 'home#index'

  resource :account, :controller => :account

  get '/logout' => 'session#destroy'
  resource :session, :controller => :session

end

app/models/user.rb
# uses bcrypt-ruby gem for password hashing be sure to config.gem it
require 'digest/sha1'
require 'bcrypt'
class User
  include MongoMapper::Document
  include BCrypt

  key :username, String, :required => true, :unique => true
  key :email, String, :required => true, :unique => true
  key :crypted_password, String
  key :reset_password_code, String
  key :reset_password_code_until, Time
 
  RegEmailName   = '[\w\.%\+\-]+'
  RegDomainHead  = '(?:[A-Z0-9\-]+\.)+'
  RegDomainTLD   = '(?:[A-Z]{2}|com|org|net|gov|mil|biz|info|mobi|name|aero|jobs|museum)'
  RegEmailOk     = /\A#{RegEmailName}@#{RegDomainHead}#{RegDomainTLD}\z/i
  
  def self.authenticate(email, secret)
    ensure_index :username
    ensure_index :email
    u = User.first(:conditions => {:email => email.downcase})
    u && u.authenticated?(secret) ? u : nil
  end
  
  validates_length_of :email, :within => 6..100, :allow_blank => true
  validates_format_of :email, :with => RegEmailOk, :allow_blank => true
  
  PasswordRequired = Proc.new { |u| u.password_required? }
  validates_presence_of :password, :if => PasswordRequired
  validates_confirmation_of :password, :if => PasswordRequired, :allow_nil => true
  validates_length_of :password, :minimum => 6, :if => PasswordRequired, :allow_nil => true
  
  def authenticated?(secret)
    password == secret ? true : false
  end
  
  def password
    if crypted_password.present?
      @password ||= BCrypt::Password.new(crypted_password)
    else
      nil
    end
  end
  
  def password=(value)
    if value.present?
      @password = value
      self.crypted_password = BCrypt::Password.create(value)
    end
  end
  
  def email=(new_email)
    new_email.downcase! unless new_email.nil?
    write_attribute(:email, new_email)
  end
  
  def password_required?
    crypted_password.blank? || !password.blank?
  end
  
  def set_password_code!
    seed = "#{email}#{Time.now.to_s.split(//).sort_by {rand}.join}"
    self.reset_password_code_until = 1.day.from_now
    self.reset_password_code = Digest::SHA1.hexdigest(seed)
    save!
  end

end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  layout 'account'
  layout 'application', :only => [:new, :create]
  before_filter :authenticate, :except => [:new, :create]

  # Show the signup form
  def new
    @user = User.new
  end

  # Create a new user account from the posted signup form
  def create
    @user = User.new params[:user]
    if @user.save
      self.current_user = @user
      redirect_to '/account'
    else
      render :new
    end
  end

  # Show the user's account profile
  def show
  end

  # Show the edit profile form
  def edit
  end

  # Update the user account from the posted edit form
  def update
  end

  # Destroy a user's account
  def destroy
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  # Show the login form
  def new
    @user = User.new
  end

  # Log the user in
  def create
    @user = User.authenticate(params[:email], params[:password])
    render :new and return if @user.nil?
    self.current_user = @user
    redirect_to account_path
  end

  # Log the user out
  def destroy
    sign_out_keeping_session!
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_message(model, field)
    return if model.blank?
    return "<div class='error_message'><p>#{model.errors[field].join('</p><p>')}</p></div>".html_safe if model.errors[field].present?
  end
end

app/views/home/index.html.haml
.sixteen.columns#slogan
  %h5 Build dungeons and populate them from your monster zoo.  Create a band of heroes to take over your enemies' dungeons.  Compete in the colosseum.  Buy and sell items, armor and weapons for your heroes.  Send heroes exploring to capture monsters for your zoo.

.eight.columns
  %h3 Login
  = render :partial => 'session/login_form'

.eight.columns
  %h3 Signup
  = render :partial => 'account/account_form'

app/views/layouts/account.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

  <!-- Basic Page Needs
  ================================================== -->
  <meta charset="utf-8">
  <title>Dungeon Maker - Account Area</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  ================================================== -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!-- CSS
  ================================================== -->
  <%= stylesheet_link_tag "application", :media => "all" %>

  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <!-- Favicons
  ================================================== -->
  <link rel="shortcut icon" href="images/favicon.ico">
  <!-- <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
  <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png"> -->

</head>
<body>



  <!-- Primary Page Layout
  ================================================== -->

  <!-- Delete everything in this .container and get started on your own site! -->

  <div class="container">
    <div class="sixteen columns">
      <h1 class="remove-bottom" style="margin-top: 40px">Dungeon Syndrome</h1>
      <h5>Version 1.1</h5>
      <hr />

      <a href="/logout">Logout</a>
      <a href="/dungeons">Dungeons</a>
      <a href="/heroes">Heroes</a>
      <a href="/market">Market</a>
      <a href="/colosseum">Colosseum</a>
       
      <hr />
    </div>
    <%= yield %>

    <div class="one-third column">
      <h3>About Skeleton?</h3>
      <p>Skeleton is a small collection of well-organized CSS &amp; JS files that can help you rapidly develop sites that look beautiful at any size, be it a 17" laptop screen or an iPhone. It's based on a responsive grid, but also provides very basic CSS for typography, buttons, tabs, forms and media queries. Go ahead, resize this super basic page to see the grid in action.</p>
    </div>
    <div class="one-third column">
      <h3>Three Core Principles</h3>
      <p>Skeleton is built on three core principles:</p>
      <ul class="square">
        <li><strong>A Responsive Grid Down To Mobile</strong>: Elegant scaling from a browser to tablets to mobile.</li>
        <li><strong>Fast to Start</strong>: It's a tool for rapid development with best practices</li>
        <li><strong>Style Agnostic</strong>: It provides the most basic, beautiful styles, but is meant to be overwritten.</li>
      </ul>
    </div>
    <div class="one-third column">
      <h3>Docs &amp; Support</h3>
      <p>The easiest way to really get started with Skeleton is to check out the full docs and info at <a href="http://www.getskeleton.com">www.getskeleton.com.</a>. Skeleton is also open-source and has a <a href="https://github.com/dhgamache/skeleton">project on git</a>, so check that out if you want to report bugs or create a pull request. If you have any questions, thoughts, concerns or feedback, please don't hesitate to email me at <a href="mailto:hi@getskeleton.com">hi@getskeleton.com</a>.</p>
    </div>

  </div><!-- container -->



  <!-- JS
  ================================================== -->
  <%= javascript_include_tag "application" %>

<!-- End Document
================================================== -->
</body>
</html>

app/views/layouts/account.html.haml
!!!
%html
  %head
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %title
      Dungeons - Logged In

  %body
    %h1 Account Overview
    %ul
      %li
        %a{:href => '/logout'} Logout
      %li
        %a{:href => '/dungeons'} Dungeons
      %li
        %a{:href => '/heroes'} Heroes

    = yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

  <!-- Basic Page Needs
  ================================================== -->
  <meta charset="utf-8">
  <title>Dungeon Maker</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  ================================================== -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!-- CSS
  ================================================== -->
  <%= stylesheet_link_tag "application", :media => "all" %>

  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <!-- Favicons
  ================================================== -->
  <link rel="shortcut icon" href="images/favicon.ico">
  <!-- <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
  <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png"> -->

</head>
<body>



  <!-- Primary Page Layout
  ================================================== -->

  <!-- Delete everything in this .container and get started on your own site! -->

  <div class="container">
    <div class="sixteen columns">
      <h1 class="remove-bottom" style="margin-top: 40px">Dungeon Critters</h1>
    </div>

    <%= yield %>

    <div class="one-third column">
      <h3>About Skeleton?</h3>
      <p>Skeleton is a small collection of well-organized CSS &amp; JS files that can help you rapidly develop sites that look beautiful at any size, be it a 17" laptop screen or an iPhone. It's based on a responsive grid, but also provides very basic CSS for typography, buttons, tabs, forms and media queries. Go ahead, resize this super basic page to see the grid in action.</p>
    </div>
    <div class="one-third column">
      <h3>Three Core Principles</h3>
      <p>Skeleton is built on three core principles:</p>
      <ul class="square">
        <li><strong>A Responsive Grid Down To Mobile</strong>: Elegant scaling from a browser to tablets to mobile.</li>
        <li><strong>Fast to Start</strong>: It's a tool for rapid development with best practices</li>
        <li><strong>Style Agnostic</strong>: It provides the most basic, beautiful styles, but is meant to be overwritten.</li>
      </ul>
    </div>
    <div class="one-third column">
      <h3>Docs &amp; Support</h3>
      <p>The easiest way to really get started with Skeleton is to check out the full docs and info at <a href="http://www.getskeleton.com">www.getskeleton.com.</a>. Skeleton is also open-source and has a <a href="https://github.com/dhgamache/skeleton">project on git</a>, so check that out if you want to report bugs or create a pull request. If you have any questions, thoughts, concerns or feedback, please don't hesitate to email me at <a href="mailto:hi@getskeleton.com">hi@getskeleton.com</a>.</p>
    </div>

  </div><!-- container -->



  <!-- JS
  ================================================== -->
  <%= javascript_include_tag "application" %>
  <!--
  <script src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
  <script src="javascripts/tabs.js"></script>
  -->

<!-- End Document
================================================== -->
</body>
</html>

app/views/session/_login_form.html.haml
= form_tag session_path do

  .form_input
    = label_tag :email, "Email"
    = text_field_tag :email

  .form_input
    = label_tag :password
    = password_field_tag :password
  
  %input{:type => "submit", :value => "Login"}

  - if defined? @user
    or
    = link_to 'Sign Up', new_account_path

app/views/session/new.html.haml
.sixteen.columns
  %h2 Login

  - if @user.nil?
    .error_message
      %p Couldn't find your account with that email and password.

  = render :partial => 'login_form'